name: hydrosat
channels:
  - default
  - conda-forge
dependencies:
  - python=3.11
  - geopandas>=0.10
  - rasterio>=1.1.5
  - omegaconf
  - jsonargparse
  - matplotlib>=3.8.2
  - pandas>=2.1.4
  - scikit-image>=0.22.0
  - pillow>=9.3.0
  - torchmetrics==1.2.0
  - pytorch-lightning==2.1.1
  - segmentation-models-pytorch==0.3.3
  - albumentations==1.3.1
  - tensorboard==2.15.1
  - transformers<=4.50.3
  - ipdb
  - requests
  - mamba
  - jupyterlab
  - ipykernel